-- Exporta la estructura de la base de datos (sin datos) como sentencias SQL, una por fila.
-- Uso: Supabase → SQL Editor → ejecutar → Export → Download CSV.
-- El resultado se guarda en supabase/esquema.sql como copia de referencia del proyecto.

with
extensiones as (
  select 0 as orden, e.extname::text as nombre,
         format('create extension if not exists %I with schema %I;', e.extname, n.nspname) as sql
  from pg_extension e join pg_namespace n on n.oid = e.extnamespace
  where e.extname <> 'plpgsql'
),
enums as (
  select 1, t.typname::text,
         format('create type public.%I as enum (%s);', t.typname,
                string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder))
  from pg_type t
  join pg_enum e on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public'
  group by t.typname
),
tablas as (
  select 2, c.relname::text,
         format(E'create table public.%I (\n%s\n);', c.relname,
           string_agg(
             format('  %I %s', a.attname, format_type(a.atttypid, a.atttypmod))
             || case
                  when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored'
                  when a.attidentity = 'a' then ' generated always as identity'
                  when a.attidentity = 'd' then ' generated by default as identity'
                  when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid)
                  else '' end
             || case when a.attnotnull then ' not null' else '' end,
             E',\n' order by a.attnum))
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
  where n.nspname = 'public' and c.relkind = 'r'
  group by c.relname
),
restricciones as (
  -- Claves foráneas al final, cuando ya existen todas las tablas
  select case when k.contype = 'f' then 4 else 3 end, (c.relname || '.' || k.conname)::text,
         format('alter table public.%I add constraint %I %s;', c.relname, k.conname, pg_get_constraintdef(k.oid))
  from pg_constraint k
  join pg_class c on c.oid = k.conrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
),
indices as (
  select 5, i.relname::text, pg_get_indexdef(i.oid) || ';'
  from pg_index x
  join pg_class i on i.oid = x.indexrelid
  join pg_class c on c.oid = x.indrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and not exists (select 1 from pg_constraint k
                    where k.conindid = x.indexrelid and k.contype in ('p','u','x'))
),
funciones as (
  select 6, p.proname::text, pg_get_functiondef(p.oid) || ';'
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind in ('f','p')
    and not exists (select 1 from pg_depend dp where dp.objid = p.oid and dp.deptype = 'e')
),
vistas as (
  select 7, c.relname::text,
         format(E'create or replace view public.%I%s as\n%s', c.relname,
                case when c.reloptions is not null
                     then ' with (' || array_to_string(c.reloptions, ', ') || ')' else '' end,
                pg_get_viewdef(c.oid, true))
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'v'
),
disparadores as (
  select 8, t.tgname::text, pg_get_triggerdef(t.oid) || ';'
  from pg_trigger t
  join pg_class c on c.oid = t.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and not t.tgisinternal
),
rls as (
  select 9, c.relname::text, format('alter table public.%I enable row level security;', c.relname)
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
),
politicas as (
  -- Incluye las del bucket de fotos (storage.objects)
  select 10, (schemaname || '.' || tablename || '.' || policyname)::text,
         format('create policy %I on %I.%I as %s for %s to %s%s%s;',
                policyname, schemaname, tablename, permissive, cmd, array_to_string(roles, ', '),
                case when qual is not null then ' using (' || qual || ')' else '' end,
                case when with_check is not null then ' with check (' || with_check || ')' else '' end)
  from pg_policies
  where schemaname in ('public', 'storage')
)
select orden, nombre, sql from (
  select * from extensiones
  union all select * from enums
  union all select * from tablas
  union all select * from restricciones
  union all select * from indices
  union all select * from funciones
  union all select * from vistas
  union all select * from disparadores
  union all select * from rls
  union all select * from politicas
) todo
order by orden, nombre;
